//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwoWayDBREST.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public string UserDayPhone { get; set; }
        public string UserStreet { get; set; }
        public string UserApartment { get; set; }
        public string UserCity { get; set; }
        public string UserProvince { get; set; }
        public string UserPostalCode { get; set; }
        public string UserEmail { get; set; }
        public long UserIDPK { get; set; }
    }
}
